### PR TITLE
Update version to v1.14.3

### PR DESCRIPTION
**Pull request by aphex3k**
Is this repository really the source for the current version of lncm specter desktop docker image? It seems abandoned since a couple of versions ago...

### CODE REVIEW

**Comment by nolim1t** [comment]
yes its the official source but there was a auto updating feature that @AaronDewes  added which pushes things automatically.

Let me take a look

**Comment by nolim1t** [comment]
latest version was 2 days ago 

https://hub.docker.com/layers/lncm/specter-desktop/v1.14.2/images/sha256-96c4cc53780282f869fa46e127894e55fa50335119f35997d9335e52a3505092?context=explore

There is also a prerelease of 1.14.3

https://hub.docker.com/layers/lncm/specter-desktop/v1.14.3-pre1/images/sha256-32ac543d01422db0e84d70d63f08fe79c2ae5d1f38f4e9bfbcebbca85ae1aac3?context=explore

It's still working so I'm closing this PR. Thanks for the pull request though. Not needed to change anything for it to do its thing :)

However if you'd like to update any documentation to reflect the above please go ahead.

**Comment by aphex3k** [comment]
I'm looking for lncm/specter-desktop:v1.14.3

**Comment by nolim1t** [comment]
Are you manually running something @AaronDewes  for triggering those auto builds or is there some sort of cron somewhere?

**Comment by AaronDewes** [comment]
It's automated.  I gave Specter a personal access token for my account that is restricted to triggering that workflow, so they can trigger a build in their CI.

**Comment by nolim1t** [comment]
Thanks for that. Specter Desktop guys controls all the automated docker builds here.

**Pull request closed without merging**
