### PR TITLE
Add docs for 1.4.2

### PR DESCRIPTION
**Pull request by nolim1t**
Add docs for [1.4.2](https://hub.docker.com/layers/lncm/specter-desktop/v1.4.2/images/sha256-9adadfbc273ffdd5e2a31240560a2d3334099a2c2cc7e9fa5bdd1c676db38f66?context=explore) and 1.4.1

### CODE REVIEW

**Comment by nolim1t** [comment]
Awaiting build then we merge

**Comment by AaronDewes** [comment]
They made a release again?!??!?!

**Comment by nolim1t** [comment]
> They made a release again?!??!?!

yeah haha.

no major bugfixes though so I wouldnt worry about any 1.4.X point releases

**Comment by nolim1t** [comment]
bear market development things

**Review by AaronDewes — APPROVED** [review]

**Pull request merged**
